version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
  postgres:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  aioodbc:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.8}
    command: sh -c "sleep 10; pytest --cov"
    volumes:
      - .:/aioodbc
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - mysql
